name: "Create reports"
on:
  workflow_dispatch:

jobs:
  reports:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.FORECASTHUB_TOKEN }}
          repository: 'covid19-forecast-hub-europe/covid19-scenario-hub-europe'

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-renv@v2

      - name: Create country reports
        run: Rscript 'code/summarise/create-report.R'

      - uses: actions/upload-artifact@v2
        with:
          name: reports
          retention-days: 8
          path: |
            reports/
